name: build-macos-arm64

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The git ref to checkout"
        required: true
        default: main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RID: osx-arm64

    steps:
      # Checkout this repo
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Prepare Managed DLLs
        run: |
          mkdir -p Vanilla/Managed
          cp -R Managed/* Vanilla/Managed/

      # Copy Managed DLLs to the expected location
      - name: Prepare Managed DLLs
        run: |
          mkdir -p Vanilla/Managed
          cp Hollow-Knight-api/Managed/* Vanilla/Managed/

      # Setup .NET
      - uses: actions/setup-dotnet@v4

      - name: Setup MSBuild
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-devel

      # Restore NuGet dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build PrePatcher
      - name: Build PrePatcher
        run: dotnet build PrePatcher -c Release -o PrePatcher/Output

      # Build Assembly-CSharp targeting macOS ARM64
      - name: Build Assembly-CSharp
        run: dotnet build Assembly-CSharp -c Release -r $RID

      # Merge macOS dylibs
      - name: Merge osx dylibs
        run: |
          wget https://github.com/konoui/lipo/releases/download/v0.9.4/lipo_linux_amd64 -O lipo
          chmod +x lipo

          mkdir -p OutputFinal
          ./lipo \
            -output libunityscenerepacker.dylib \
            -create \
            ./Assembly-CSharp/packages/unityscenerepacker/2.4.0/runtimes/osx-*/native/libunityscenerepacker.dylib

          mv libunityscenerepacker.dylib OutputFinal/

      # Upload build artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-build
          path: OutputFinal/
          retention-days: 30
